[uwsgi]
module = wsgi:app
enable-threads = true
lazy-apps=true

master = true
processes = 4
threads = 2
enable-threads = True

socket = myproject.sock
chmod-socket = 660
vacuum = true

die-on-term = true

#location of log files
#logto = /var/log/uwsgi/%n.log
